- scripts/install-tor-only.sh
This reverts commit 85b31f4baef7709ba57d5f05abdb75b11502865b.
> Revert "Update install-tor-only.sh"

- terms-of-service.md
Guessing this was an oversight.
> Fills in "California, US" in terms of service

- scripts/install.sh
I think it's best practice to have the user be in the same directory after this if/else, no matter which branch they take.
> Return to $HOME after git reset

- README.md
Move team information to the project-info repo.
> Relocate Team Info

- static/style.css
> removes some whitespace from static/style.css

- README.md
> adds a little whitespace for testing purposes

- assets/nginx/nginx.conf
- assets/scripts/install-public-plus-tor.sh
- assets/scripts/install-tor-only.sh
Removing country code from privacy preserving logging. Not needed for our use case.
> remove country code from private logging

- admin.py
- app.py
- install.sh
- migrate_db.py
- static/style.css
- templates/admin.html
- templates/base.html
- templates/confirm_disable_2fa.html
- templates/enable_2fa.html
- templates/inbox.html
- templates/login.html
- templates/register.html
- templates/settings.html
- templates/show_qr_code.html
- templates/submit_message.html
- templates/verify_2fa_login.html
flag users as admins
basic metrics:
no. of users
no. of users with 2fa enabled 
no. of users with a pgp key
> Add admin view

- app.py
- install.sh
- static/script.js
- templates/base.html
- templates/submit_message.html
> Add Client-Side Encryption with OpenPGP.js

- app.py
- install.sh
> Add SSL to MySQL DB Connections

- assets/scripts/install.sh
- static/style.css
- templates/index.html
Making the interface distinct from the hosted service for clarity to users.
Goals:
- Prevent the opportunity to forge verified badges
- Minimal UI to match the e-paper display + product use case and feature set
- Light and dark modes
- Use the full viewport for the message portal
> Personal Server-Specific Styling 

- app.py
- assets/scripts/helper.sh
- assets/scripts/install.sh
- assets/scripts/uninstall.sh
- requirements.txt
- static/style.css
- Include Redis for limiter storage
- Add secret key generation in install
- Flask limiter enforces 10 requests per page per minute
- Switching from RPiOS Full to Lite
- Install Git in helper
- Add uninstaller
- Update few styles
> Application-side DOS Mitigation with Flask-Limiter. 

- app.py
- static/style.css
- templates/submit_message.html
- Encourage users to download Tor Browser for better privacy. 
- Educate about IP monitoring
> Show IP address on submit message form

- privacy-policy.md
- Clarify data retention practices, specifying the retention period after account deletion or inactivity
- Expand on user rights, including data portability, objection to processing, and the right to lodge complaints
- Add information about the use of essential cookies and how users can manage their preferences
- Explain international data transfers and the legal mechanisms relied upon
- Specify the age restrictions for using the app and the handling of personal information from minors
- Include a disclaimer about third-party links and the applicability of the privacy policy
- Describe the breach notification process in the event of a data breach affecting personal information
- Add an "Effective Date" to indicate when the current version of the policy came into effect
These changes aim …
> Enhance privacy policy with additional clauses and clarifications

- Makefile
- hushline/__init__.py
- hushline/settings.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_routes.py
> basic pytest configuration

- install.sh
This pull request implements recommended enhancements to the installation script, addressing points raised in issue #284 and incorporating best practices as suggested by `shellcheck`. The focus was on improving script reliability and code efficiency without altering the script's core functionality.
- **Introduction of `set -euo pipefail`:** Ensured immediate exit on failure, prevention of using unset variables, and failure on pipe errors, enhancing the script's fault tolerance.
- **Revised Command Execution Logic:** Replaced `A && B || C` constructs with explicit if-then-else statements, addressing potential logic flaws highlighted by `shellcheck` (SC2015).
- **Optimized File Writing Operations:** Consolidated multiple outputs into single file write operations to reduce system calls and …
> Refinements to Installation Script for Enhanced Stability and Efficiency

- hushline/__init__.py
- install.sh
- Encapsulated the `list_keys` function within a Flask CLI command group named `debug`. This helps organize debugging-related commands and keeps the main command namespace clean.
- Improves discoverability and organization of debugging commands without cluttering the primary command space.
> Organize Debug Commands into CLI Command Group

- hushline/__init__.py
Removes the setup for logging to a file using `RotatingFileHandler`, including the initialization, configuration, and addition of the file handler to the app's logger.
> Remove logging to file

- hushline/__init__.py
- hushline/crypto.py
- hushline/routes.py
This PR streamlines the access to environment variables across the application, ensuring consistency and reducing the reliance on intermediary variables for configurations. By directly utilizing `os.environ.get()`, we enhance the readability and maintainability of the code. Changes include:
- Standardized use of `os.environ.get()` for accessing environment variables in `__init__.py`, `crypto.py`, and `routes.py`.
- Ensured consistent handling of default values where applicable.
- Removed temporary variables previously used for storing environment variables, simplifying the configuration setup.
These modifications contribute to a cleaner codebase, facilitating easier future adjustments to the configuration process.
> Optimize Config via Direct Env Var Access

- install.sh
1. **Dedicated Non-Root User Creation:**
- A new system user, `hushlineuser`, with minimal permissions, is now created during the installation process. This user is specifically dedicated to running the application instead of `root`.
- Adjustments to file permissions removing elevated privileges.
2. **Account Deletion Confirmation Dialog:**
- Added a JavaScript-based confirmation dialog that was accidentally removed in the refactor, prompting users for confirmation before proceeding with account deletion.
The installation script now includes steps to create the `hushlineuser` user and adjust the necessary permissions:
```bash
HUSHLINE_USER="hushlineuser"
HUSHLINE_GROUP="www-data"
if ! id "$HUSHLINE_USER" &>/dev/null; then
echo "Creating a dedicated user: $HUSHLINE_USER..."
useradd -r -s …
```
> Implementation of Non-Root User

- .github/workflows/merge-to-main.yml
- .github/workflows/pull-request.yml
- migrations/env.py
Relates to #262 but doesn't quite close it
> fix ci jobs

- hushline/settings.py
- Increase PGP Key Length to 100,000 characters. 
- Fix fail-state when an invalid key is added.
> Settings Bug Fixes

- .github/workflows/merge-to-main.yml
- tests/test_registration_and_login.py
Use `os.getcwd()` function to get the current working directory.
> Update testing DB path

- hushline/templates/submit_message.html
Fix broken links on submit_message page
> Update Docs Links

- .gitignore
- hushline/routes.py
- hushline/static/js/directory.js
- hushline/utils.py
- tests/test_directory.py
- No more DB calls for searching.
- JSON file is re-created when a user opts in to the directory listing.
> Create JSON search index

- Dockerfile
Run unittests during container build
> run tests as part of docker container build

- .github/workflows/build-and-deploy-release.yml
- hushline/routes.py
- hushline/static/js/directory.js
- hushline/utils.py
> Simplify directory

- hushline/static/css/style.css
- padding
- fonts
-  button states
**Before:**
**After:**
**Before:**
**After:**
> UI fit and finish

- hushline/static/css/style.css
Hiding default checkbox from being visible.
> fixed visible checkbox from showing

- hushline/static/js/directory.js
Forgot to update one of the Verified badges...
> Update Verified Badge in Directory

- hushline/static/css/style.css
- hushline/templates/submit_message.html
> Add link to learn more about verification on submit page

- hushline/templates/settings.html
https://github.com/user-attachments/assets/3169d5a9-79df-4664-b0a0-93960cf62255
For issue https://github.com/scidsg/hushline/issues/421
> Resolved admin tab in settings

- .github/workflows/build-and-deploy-release.yml
Instead of using a static app id, look it up via doctl by app name.
> app id may be unstable so look it up by app name when deploying

- hushline/static/css/style.css
Mainly standardization of spacing.
> Css Cleanup

- hushline/static/css/style.css
Some crazy formatting happening:
Fixed:
> Fix Admin Settings UI

- hushline/static/css/style.css
- hushline/templates/directory.html
- Better description of Hush Line
- Includes directory information encouraging users/whistleblowers to contact a lawyer first
- Encourages users not to steal info hastily
> Add verbose directory info

- hushline/templates/directory.html
> Shorten Directory Intro

- hushline/templates/directory.html
> UI text updates for more brevity

- hushline/templates/base.html
- Fixing the broken social link
- Update description text
> Fix broken <meta> links

- hushline/routes.py
- hushline/static/css/style.css
- hushline/templates/submit_message.html
- tests/test_submit_message.py
Adds CAPTCHA which serves a simple math problem through an accessible input.
> Accessible Math CAPTCHA

- hushline/static/css/style.css
- hushline/static/js/settings.js
- hushline/templates/settings.html
- Moves "Update" button into parent `fieldset`. 
- Updates `select` menu for more consistent styling
- Updates toggle ui order to match directory opt-in layout
> Update SMTP UI

- Makefile
- dev_env.sh
- hushline/__init__.py
- hushline/model.py
- hushline/routes.py
- hushline/settings.py
- hushline/static/css/style.css
- hushline/static/js/settings.js
- hushline/templates/settings.html
- hushline/utils.py
- migrations/versions/6e53eac9ea14_smtp_encryption_protocol.py
- pyproject.toml
- tests/auth_helper.py
- tests/test_settings.py
Addresses https://github.com/scidsg/hushline/issues/401
> Smtp settings

- hushline/static/css/style.css
- Removes border-radius from header
- Moved the header directly under the banner
- This makes the public website and the app visually aligned
> Fix Header Placement and Style

- hushline/static/css/style.css
- hushline/templates/profile.html
- hushline/templates/settings.html
- Tightens/makes consistent the UI spacing
- Remove all placeholders except the first with Signal
> Updates form spacing

- hushline/settings.py
Remove the call to `asyncio.run()` and make the route handler async.
> Me async route

- Dockerfile
> Stop running tests in docker

- hushline/model.py
- hushline/settings/__init__.py
> remove commits from property setters and make them explicit

- hushline/__init__.py
- hushline/settings/__init__.py
- hushline/templates/directory.html
- hushline/templates/profile.html
- hushline/templates/settings/alias.html
- hushline/templates/settings/auth.html
- hushline/templates/settings/profile.html
- Enables `StrictUndefined` in development mode
- Fixes bugs caught by the introduction of this change
Fixes #577 
Depends on #600 (needs to be merged first)
> Dev env jinja errors

- poetry.lock
- pyproject.toml
> replace bs4 with (correct) beautifulsoup4

- .github/workflows/build-and-deploy-release.yml
- .github/workflows/build-latest.yml
- Dockerfile.dev
- Dockerfile.prod
broke some stuff, now am a fixin'
> fix docker builds

- hushline/model.py
- poetry.lock
- pyproject.toml
- removed types for `setuptools`
- moved types for `requests` into dev dependencies
> cleaned up dependencies

- .github/workflows/tests.yml
- Makefile
- docs/DEV.md
- tests/conftest.py
> flag to test using sqlalchemy or alembic for db init

- hushline/static/css/style.css
- hushline/templates/base.html
- hushline/templates/premium-select-tier.html
- hushline/templates/premium-waiting.html
- hushline/templates/premium.html
- hushline/templates/settings/advanced.html
- hushline/templates/settings/index.html
> Glenn's Stripe Visual Updates Try 2

- hushline/routes.py
- hushline/settings/__init__.py
1. We want this because it improves UX for people who submit on the very edge of the 30s window but also especially for people with slow connections
2. It will likely help with flaky tests (not 100% sure, but marking as "fixed" regardless"
Fixes #587
> increase window for TOTP validity

- hushline/templates/premium/business-features.html
- hushline/templates/premium/free-features.html
- hushline/templates/profile.html
This aligns the app page with the information listed on the public site.
> Update Business Features HTML + Bug Fix

- hushline/static/css/style.css
- hushline/templates/premium-select-tier.html
- hushline/templates/premium.html
To adjust the size of `<main>` I removed the `base.html` integration and included the code in the page itself. 
This is to make the plan selection page wider to accommodate more information.
> update plan selection page width

- hushline/routes.py
> order users in directory by is_admin then display/username

- hushline/static/css/style.css
Replaces with `--font-sans-bold`
> Removes native bold styling

- hushline/premium.py
pedantic bullshit. unless @micahflee had a reason for doing this?
> user logger.info (not error) when worker starts

- hushline/premium.py
- hushline/templates/directory.html
- hushline/templates/premium.html
- tests/test_premium.py
Fixes #706 
- uses a flash message to return responses. 
- fix template to point to appropriate routes
- refactors tests
- Includes update to intro paragraph to contain a link back to hushline.app.
- Fixes link to point to current docs.
> fixes stripe json response

- hushline/config.py
- scripts/prod_start.sh
> Gracefully handle starting Hush Line in prod when STRIPE_SECRET_KEY is not set

- hushline/static/css/style.css
> Tabs Agian

- hushline/static/css/style.css
- hushline/templates/message.html
- hushline/templates/reply.html
- hushline/templates/submission_success.html
1. CSS Updates:
• Refactored .message, .message-container, and .user styles for consistent padding, borders, and box shadows.
• Introduced .action-model styles for aligned and spaced action buttons/forms.
• Improved styles for .message-meta and .message-header to enhance readability.
2. Template Enhancements:
• Consolidated metadata display for messages in message.html and reply.html into reusable message-container structure.
• Updated submission_success.html:
• Removed redundant p tags around “Copy Link” button for cleaner layout.
• Retained “Do not share this link” warning for emphasis.
3. Code Simplifications:
• Reduced redundant markup in reply.html by aligning it with message.html.
• Removed unnecessary styles and elements for better maintainability.
4. User Feedback Improvements:
• …
> style tweaks

- hushline/settings/__init__.py
> ensure all settings page are passed a user object

- hushline/static/css/style.css
- hushline/static/js/message_success.js
- hushline/templates/submission_success.html
Add UI feedback when copy button is clicked.
https://github.com/user-attachments/assets/d1af22cf-038f-44e0-9ee2-4d870888d3b0
> add feedback to copy interaction

- hushline/static/css/style.css
- hushline/static/js/global.js
- hushline/static/js/settings.js
- hushline/templates/base.html
- hushline/templates/settings/guidance.html
> onboarding interaction stuff

- hushline/settings/forms.py
- hushline/static/css/style.css
- hushline/templates/settings/update_profile_header.html
Improvements to the user experience for customizing profile headers and refines form and style elements:
1. Label Update: Updated `UpdateProfileHeaderForm` to use a clearer, user-friendly label for the `template` field (“Custom Profile Header”).
2. Styling Improvements: Added padding, margin adjustments, and formatting rules to form and list elements in `style.css` for better visual consistency.
3. Template Instructions: Enhanced the instructional content in `update_profile_header.html` to clarify variable usage, provide examples, and improve readability.
> Updated Settings content

- Makefile
> Revert "fix makefile migrations"

- hushline/templates/base.html
- hushline/templates/premium.html
- hushline/templates/profile.html
- hushline/templates/settings/admin.html
- hushline/templates/settings/advanced.html
- hushline/templates/settings/aliases.html
- hushline/templates/settings/auth.html
- hushline/templates/settings/base.html
- hushline/templates/settings/branding.html
- hushline/templates/settings/email.html
- hushline/templates/settings/guidance.html
- hushline/templates/settings/profile-forms.html
- hushline/templates/settings/profile.html
- hushline/templates/settings/replies.html
- scripts/dev_data.py
preparation for work for #861. making this its own PR to avoid a horrible diff later.
zero functional changes, only factoring out all the settings page wrappers. and some DRY applied to the dev data script.
> Minor refactors

- hushline/settings/common.py
- tests/test_verify_url.py
> improved logic for label verification

- hushline/settings/common.py
> preferred scheme override for url verification

- hushline/forms.py
- hushline/model/enums.py
- hushline/routes/inbox.py
- hushline/static/css/style.css
- hushline/templates/inbox.html
- hushline/templates/reply.html
- hushline/templates/settings/replies.html
- tests/test_inbox.py
- tests/test_replies.py
> inbox tabs

- hushline/settings/common.py
> fix bug with deletions of profile bio fields/values

- docs/README.md
- hushline/config.py
- hushline/settings/notifications.py
- hushline/templates/settings/notifications.html
> Make SMTP customizable even when default settings are used

- hushline/model/username.py
- hushline/routes/forms.py
- hushline/settings/forms.py
> allow useranmes to be 3 characters

- Dockerfile.prod
- assets/js/settings-fields.js
- hushline/__init__.py
- hushline/forms.py
- hushline/model/field_definition.py
- hushline/settings/common.py
- hushline/settings/forms.py
- hushline/templates/base.html
- hushline/templates/directory.html
- hushline/templates/profile.html
- hushline/templates/settings/profile-field-form.html
- hushline/templates/settings/profile-forms.html
- hushline/templates/settings/replies.html
- hushline/templates/vision.html
- tests/test_verify_url.py
- add warning on deletion
- prevent updating of field types once created
fixes #969
> warning on field deletion or edit

- Makefile
- docs/DEV.md
> docs for database migrations
