scidsg/hushline

app.py

:wave: 
this PR includes 2 small bugfixes:
1.) startup app even if no `NOTIFY_SMTP_PORT` is given as env var
2.) fix the `pgp_owner_info` endpoint for pgp keys that have no expiration date

Fix some app startup issues 

---

.gitignore
Dockerfile
docker-compose.example.yaml

This begins to package Hush Line using Docker containers. Here's how to test it:
- Make sure you have [Docker Desktop](https://www.docker.com/products/docker-desktop/) installed.
- Save a copy of `docker-compose.example.yaml` as `docker-compose.yaml` and edit it to add your correct settings.
- Put a copy of your PGP public key in the file `public_key.asc`.
- Run: `docker-compose up`
It should start a Hush Line server which you can load at http://localhost:5000/.
(This isn't quite done yet-- I need to add Tor onion service support.)

Start packaging in a Docker container

---

.vscode/settings.json
Dockerfile
app.py
docker-compose.example.yaml
static/main.js
templates/index.html

This single PR changes several things. Sorry about doing it all at once, but it just seemed simpler this way.
Since #108, now you can define all of the Hush Line settings directly in a `docker-compose.yaml` file. Here's the example docker-compose file:
```yaml
version: "3.9"
services:
app:
build: .
ports:
- "5000:80"
volumes:
- ./public_key.asc:/app/public_key.asc:ro
environment:
- RECIPIENT_NAME=Your Name
- RECIPIENT_EMAIL=recipient@example.com
- SENDER_EMAIL=sender@example.com
- SMTP_SERVER=smtp.gmail.com
- SMTP_PORT=465
- SMTP_USER=username@example.com
- SMTP_PASSWORD=yourpassword
- TITLE=🤫 Hush Line
- CLOSE_APP_LINK=https://en.wikipedia.org/wiki/Tina_Turner
- PGP_ENABLED=true
- PGP_FILENAME=public_key.asc
```
The `TITLE` and `CLOSE_APP_LINK` environment variables let you change how …

Add some branding, make PGP optional, and separate email sender and receiver

---

scripts/waveshare-2_13in_eink-display.sh
scripts/waveshare-2_7in-eink-display-v1.sh
scripts/waveshare-2_7in-eink-display.sh

In all 3 waveshare e-ink display scripts, use the [`raspi-config` Command Line Interface](https://www.raspberrypi.com/documentation/computers/configuration.html#raspi-config-cli) to enable the Pi's SPI interface rather than tossing the user into the raspi-config TUI with instructions. 
Note: Perhaps counterintuitively, [`0` is to enable and `1` is to disable](https://www.raspberrypi.com/documentation/computers/configuration.html#spi-nonint).
This change seems to work well for Blackbox. See [Blackbox PR #16](https://github.com/scidsg/blackbox/pull/16) for more info.

Use `raspi-config` CLI to enable SPI

---

templates/index.html

No disrespect to the "Queen of Rock 'n' Roll", but rather than hard-code the "Close App" button to [Tina Turner's Wikipedia page](https://en.wikipedia.org/wiki/Tina_Turner), this instead links to [https://en.wikipedia.org/wiki/Special:Random](https://en.wikipedia.org/wiki/Special:Random), which, as I understand it, takes users to a random Wikipedia page.
I don't know if either stance matters much -- just thought I propose this to start a discussion/offer another slightly less arbitrary solution. I guess theoretically investigators could look for visit's to Tina Turner's Wikipedia page as a piece of metadata?

Close App links to random Wikipedia page

---

README.md

Now reads `curl --proto '=https' --tlsv1.2 -sSfL https://install.hushline.app | bash`, matching [documentation](https://scidsg.github.io/hushline-docs/book/installation/tor-only.html#1-run-the-installer).

Update curl flags in README

---

scripts/README.md

Kind of forgot we had a little README in the `scripts/` directory. 
I added a note at the top, removed the command for a now-deleted script, and updated the `curl` flags for the remaining commands (I don't think they need the `-L` flag).

brings srcripts README up-to-date

---

app.py

Formats `app.py` with [Black](https://github.com/psf/black/), a popular and opinionated Python formatter. 
It seems to have mostly changed some single quotes to double quotes and tweaks number of blank lines between some methods. I don't think anything that will break anything.
I just ran `app.py` through the `black` command-line tool as a one-time thing for this PR. If we all want to [set up Black in our text editors, that's possible](https://black.readthedocs.io/en/stable/integrations/index.html).
I noticed that [Micah did this in his PR](https://github.com/scidsg/hushline/commit/d28e552bfbf562ceb54fc22a13b586571b8bf017) that later got reverted. Pretty sure it wasn't for the Black formatting.

Formats app.py Python code using Python formatter Black

---

scripts/install-public-plus-tor.sh

Fixing the other instance of this code. See #132 .

Adds parenthesis to be more explicit in public install script

---

scripts/install-tor-only.sh

I found the lack of immediate feedback after entering/submitting the public PGP key through the terminal a little worrisome as a user. This PR adds a short `echo` message immediately after the prompt for the key, just to tell the user that they submitted their key correctly (we hope) and that the script has moved on to other tasks (and that they can just chill and don't have to provide more information at the moment).
**I haven't tested this**

Add "PGP key received" message for user peace of mind

---

scripts/install.sh

This change fixes a bug I was experiencing on my Pi (Bookworm) in which the Hush Line install script would get "stuck" on the first whiptail prompt (I was unable to get past it by hitting enter). 
Running the simple `reset` command, with its default flags, before the first whiptail call appears to fix the issue for me. 
I don't think the command will have any adverse side effects for users who were not having my issue with the whiptail prompt(s).

`reset` terminal window before first whiptail prompt

---

app.py

I ran `app.py` through the Black formatter. It makes this long `return` statement a bit more readable. Don't think it'll affect functionality.

Format app.py

---

assets/scripts/install-public-plus-tor.sh
assets/scripts/install-tor-only.sh
templates/index.html

Proposition to change the link redirection on the "Close App" button from a random Wikipedia topic page to the main Wikipedia start page: https://www.wikipedia.org 
This would reduce the risk of an "unlucky roll" where a user might get a random Wikipedia page topic that in context might be inappropriate or even dangerous to the situation. 
It is a relatively low risk and the randomness was a creative feature but it would likely be safer to keep the redirection result constant.

Modify Close App button link to main Wikipedia page

---

hushline/__init__.py
hushline/ext.py
hushline/model.py
hushline/routes.py
hushline/settings.py
pyproject.toml

- Introduced Passlib's CryptContext for hashing passwords using bcrypt scheme. Ensured backward compatibility by marking bcrypt as the default scheme and enabling auto deprecation for future upgrades.
- Modified the `password_hash` property setter in the User model to hash plaintext passwords with Passlib before encrypting and storing the hash. This ensures that passwords are securely managed and stored in an encrypted and hashed format, enhancing security.
- Added a `verify_password` method to the `User` model for decrypting and verifying password hashes against plaintext passwords using Passlib. This method supports secure password verification during user authentication processes.

Refactor User model to use Passlib for secure password hashing

---

admin.py
hushline/model.py
hushline/routes.py
hushline/settings.py
hushline/templates/inbox.html
hushline/templates/secondary_user_settings.html
hushline/templates/submit_message.html

Renamed the `SecondaryUser` model to `SecondaryUsername`. This is to make it clearer what the model is about. It's not about users; it's about their usernames.
- Renamed the class from `SecondaryUser` to `SecondaryUsername`.
- Updated the table name in the DB from `secondary_user` to `secondary_username`.
- Fixed all references to this model in the code, including relationships and foreign keys. Wherever we had `secondary_users`, it's now `secondary_usernames`.
- Updated foreign keys in the `Message` model to link to `secondary_username.id` instead of `secondary_user.id`.
- Adjusted the backref in the `User` model to match the new naming.
The old name was misleading. This change makes our model names match what they actually represent.
- Test the parts of the app that use this model to …

Renamed SecondaryUser to SecondaryUsername

---

pyproject.toml

Updated `pyproject.toml` to correctly include the hushline directory under package definitions. This change fixes the issue where Poetry could not find the package files, ensuring the project is correctly installed and dependencies are managed.
Error addressed:
```
(venv) glennsorrentino@m1 hushline % poetry install
Installing dependencies from lock file
No dependencies to install or update
Installing the current project: Hush Line (0.0.1)
Warning: The current project could not be installed: No file/folder found for package hush line
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of …
```

Fixed Poetry package inclusion for hushline directory in `pyproject.toml`

---

.github/workflows/publish_container.yml
pyproject.toml

There are various ways to deploy on Digital Ocean App Platform, but the simplest seems to be from a container image hosted on a container registry. This PR adds a GitHub Action workflow to automatically build new container images on every push to the `main` branch, and publish them to the GitHub Container Registry.
This works, but right now the package visibility is private and it can only be accessed with authentication. Making it public would be simpler for deployment (I don't need to store GHCR credentials in Digital Ocean) and it also means others will be able to use the container image that gets built here.
@glenn-sorrentino can you help make it public? Here's the package settings: https://github.com/orgs/scidsg/packages/container/hushline%2Fhushline/settings. Can you scroll down to …

Automatically publish container images to GitHub Container Registry

---

hushline/routes.py

The default flask-limiter limits are `["200 per day", "50 per hour"]`, but the Digital Ocean health check route gets hit way more frequently than that. This PR fixes this.
However, #369 also fixes that by just removing the limits. So if we decide to merge that PR, then we can go ahead and close this one. If we're not sure, we should merge this PR first just to fix the immediate problem.

Allow lots of requests to /health.json

---

hushline/generate_invite_codes.py
hushline/model.py
tests/conftest.py
tests/test_registration_and_login.py

This fixes #373.
I fixed it by setting environment variables in `tests/conftest.py` _before_ running `app = create_app()`, so that when the `create_app()` function initializes the database, it initializes the in-memory sqlite database, instead of using the database from the actual environment.
This fixed most of the issue, but then I ran into a problem with the `test_user_registration_with_invite_code_enabled` test. This created the invite code by running a function in the `generate_invite_codes.py` script, but this is a standalone script and again was using the wrong database. So I fixed that by just creating an InviteCode object in the test directly.

Use separate test databases, and stop deleting the dev database

---

docker-compose.yaml
hushline/__init__.py

For PostgreSQL, we're using an adapter called [psycopg](https://pypi.org/project/psycopg/). In order to tell SQLAlchemy to use this adapter, the database URI needs to start with `postgresql+psycopg://`, not `postgresql://`, but otherwise it's the same.
This PR makes it so if the app is configured to use postgres, it always uses psycopg. If it's configured to use a different database (like sqlite), it doesn't change it.
This way, we can set `SQLALCHEMY_DATABASE_URI` to directly be the managed database connection string in prod.

Make postgresql database URIs use psycopg

---

hushline/__init__.py

If there's an environment variable `ONION_HOSTNAME`, this adds the [Onion-Location](https://community.torproject.org/onion-services/advanced/onion-location/) HTTP response header to every request. But if `ONION_HOSTNAME` is not set, then it doesn't add the extra header.
Onion-Location tells Tor Browser that there's an onion site version of the website, and it shows a ".onion available" button in the address bar. If the user clicks it, it redirects to the onion site specified in Onion-Location.
This PR takes into account what page the user is at right now. So if they're at `/directory`, the Onion-Location header will bring them to the `/directory` page of the onion site.

Add the Onion-Location header to HTTP responses

---

hushline/static/css/style.css
hushline/templates/base.html

1. Removed `z-index` property from styles. Edit: Added `z-index: 10` without altering index value on show/hide
2. Using `transform` instead of `top` for smoother transitions.
3. Updated the hierarchy of the messaging element so it's top level for the screen reader to announce first once it appears on the page.
https://github.com/scidsg/hushline/assets/15894356/09eda57c-f6d8-495f-8507-8cf9f96b1736
**Update screenshots:**

Modifications to flash messages

---

hushline/static/css/style.css
hushline/static/js/settings.js
hushline/templates/settings.html

1. Moved checkbox into a toggle component.
2. Tested keyboard only and with mouse.
3. Not displaying button "save" button. Will auto save when toggling element.
Demo:
https://github.com/scidsg/hushline/assets/15894356/8e4bf306-15c1-4f8e-a697-efa3548cadd2
Screenshots:

update settings public user directory toggle

---

hushline/static/css/style.css
hushline/static/js/settings.js
hushline/templates/settings.html

Added word count to update on `keyup` to inform user how many characters they have in their bio.
Example:
https://github.com/scidsg/hushline/assets/15894356/eefd98cc-181b-48f1-a2ad-150802cef40f

implemented word count for setting bio

---

hushline/static/css/style.css
hushline/static/js/submit-message.js
hushline/templates/submit_message.html

If a display name uses an abbreviation, like Science & Design, Inc. does, the helper text on the submit message page renders with two periods. This fix uses JS to find instances of two periods in any text with the `.helper` class and renders with one.
Live example on https://tips.hushline.app/submit_message/scidsg
The updated rendering:

Fix double period punctuation 

---

hushline/static/css/style.css
hushline/templates/directory.html

Allowing tabs to be in the tab order and using `button` elements instead
Example below is shown using keyboard (tabbing) only:
https://github.com/scidsg/hushline/assets/15894356/eefb9bbc-b2f5-4449-a5a4-8aae10b801c3

Fixed accessibility for directory tabs 

---

hushline/model.py
hushline/routes.py
hushline/static/js/directory.js
hushline/static/js/submit-message.js
hushline/templates/directory.html

1. Fixed JS to render Report account
2. Created endpoint to check if session user to conditionally render link
https://github.com/scidsg/hushline/assets/15894356/b7ee6100-6693-4dbd-b87d-4c31e58c76b3

Resolved report link visibility

---

hushline/templates/settings.html

Converted tabs into `button` elements to get native tabbing. Allows keyboard only users to set active tabs 
Example:
https://github.com/user-attachments/assets/722eedd7-b585-4244-9797-71a6faa9f8be

tab indexing on settings

---

hushline/static/js/submit-message.js

Right now in Hush Line when submitting a message it's possible to click "Send Message" and then a second later click it again, which ends up sending two messages. This fix makes it so that when the user clicks submit and the form starts processing the button becomes disabled.
Added js:
```js
document.addEventListener("DOMContentLoaded", function() {
...
document.getElementById('messageForm').addEventListener('submit', function() {
document.getElementById('submitBtn').disabled = true;
});
});
```

Fix Message Debouncing

---

hushline/static/js/directory.js

This is required for #407.
So far, Hush Line has always been hosted directly at a domain name, such as `https://tips.hushline.app`, but never at a path, like `https://hushline.app/tips`. Someo ne of the javascript makes ajax requests to paths like `/directory/users.json`, but if the app is hosted at `/tips`, this need to be updated to actually make requests to `/tips/directory/users.json`.
This PR does that, for `directory.js`, which right now is the only js that makes ajax requests.
To test it out:
```sh
poetry shell
export SCRIPT_NAME=/tips
source dev_env.sh
gunicorn "hushline:create_app()" -b 0.0.0.0:8080
```
Now if you load http://localhost:8080/ you'll get a 500 error, but this is to be expected:
```
gunicorn.http.errors.ConfigurationProblem: Configuration problem: Request path '/' …
```

Make ajax requests with the correct prefix

---

.github/workflows/build-and-deploy-release.yml
.github/workflows/tests.yml

The deploy job has a step that is supposed to wait for a deployment to complete before completing, but the command it runs doesn't exist in doctl. This PR updates the job to pass the `--wait` flag to the command which initiates the deployment.

remove "Wait for deployment to finish" step from deploy job

---

hushline/static/js/directory.js
hushline/templates/base.html
hushline/templates/confirm_disable_2fa.html
hushline/templates/directory.html
hushline/templates/inbox.html
hushline/templates/login.html
hushline/templates/rate_limit_exceeded.html
hushline/templates/register.html
hushline/templates/secondary_user_settings.html
hushline/templates/settings.html
hushline/templates/show_qr_code.html
hushline/templates/submit_message.html
hushline/templates/verify_2fa_login.html

This is required for #407.
There are several links to routes that were hard-coded instead of using `url_for()`, which makes all of those links broken when there's a URL prefix. This fixes them all.
Also, it formats all of the HTML using the default Visual Studio Code HTML formatter.

Update templates to use url_for()

---

hushline/static/css/style.css

All fixes are visual nits that occur during focus or hover states.
**Before:**
https://github.com/user-attachments/assets/c2917248-5c95-46a1-bfe2-15ba49738b9e
**After:**
https://github.com/user-attachments/assets/35b46f3b-462b-42d9-95f8-3f67c9716936
**Before:**
https://github.com/user-attachments/assets/bce08be9-0881-414c-aeb9-bcfd1bba9a7f
**After:**
https://github.com/user-attachments/assets/a9252599-e0d5-42f5-93b3-2d07a9bf7fe9
**Before:**
**After:**

Visual Noise on Tabs and Buttons

---

hushline/static/css/style.css

the mobile nav menu's alignment was centered - updated to `start`.
**Before:**
**After:**

Update mobile nav alignment

---

hushline/static/css/style.css
hushline/templates/submit_message.html

Closes #427 
Removes the badge container div if the user is not an admin or verified + some spacing tweaks.

Fix Empty Badge Container

---

hushline/static/css/style.css

Okay, correcting the fix from before. Basically, the 0px border-radius on the tab wasn't having the same effect as using 0em or 0rem. The gap that I tried fixing before is now more uniformly addressed.

Fix the fix

---

hushline/static/css/style.css

add transparent border bottom for label alignment

---

hushline/templates/base.html
hushline/templates/directory.html

This is required for #407.
There were two static images in the templates that weren't using `url_for()`, resulting in broken images. This should fix it. (I also auto-formatted the HTML.)

Use url_for for a few /static/img paths we missed

---

hushline/static/css/style.css
hushline/templates/directory.html

minimizes margin-bottom on directory intro.
before:
after:

fix intro gap for unauth directory

---

.github/workflows/build-and-deploy-release.yml
.github/workflows/build-latest.yml

Docker builds currently take ~30 minutes across both architectures. Container builds benefit from caching as the lower layers rarely change.  This PR enables reading from and writing to the github actions.

use the gha docker build cache

---

.github/workflows/build-and-deploy-release.yml
.github/workflows/build-latest.yml

An inadvertent tab prevented parsing the workflows.

fix whitespace in build cache parameters

---

hushline/templates/base.html
hushline/templates/settings.html

- Update Email tab to read `Email & Encryption`.
- Add conditional help text for PGP linking to our getting started docs
- Fix global title formatting
https://github.com/user-attachments/assets/eb566055-9eae-4c5b-b995-a55a3d7aeac2

Update email tab label and PGP heading

---

hushline/static/js/directory.js
hushline/static/js/global.js
hushline/static/js/settings.js

Resolved issue where if you were to go to the `All` tab the highlight functionality wouldn't work. 
In this added the tab functions to be attached to the `window` so we can call these functions in various JS files.
Example:  `directory.js` can call these  `tab functions` that live in `global.js` and also run other functions inside of these events like:  `handleSearchInput` and `updatePlaceholder`).
``` 
tabs.forEach(tab => {
tab.addEventListener('click', function(e) {
window.activateTab(e, tabs, tabPanels);
handleSearchInput(); // Filter again when tab changes
updatePlaceholder();
});
tab.addEventListener('keydown', function(e) {
window.handleKeydown(e)
});
});
```

reworked tab functions to be attached to window

---

hushline/static/css/style.css
hushline/templates/submit_message.html

Changes include:
- Add bio to submit message page
- Move encryption status above submit button

Add Bio to Submit Message Page

---

.github/workflows/tests.yml

1. It would make sharing test results on PR branches easier if the basic test suite was enabled on all pushes to any branch.
2. The pull_request setting is redundant, since a push must occur for a branch to be viewable on GitHub, so that can be removed.
Sharing [test results](https://github.com/rmlibre/hushline/actions/runs/10049396828/job/27775340599) like these would be enabled by this change.

ci: enable basic tests on all branches & the sharing of results

---

hushline/static/css/style.css

While the base font size is 1rem, which should be 16px, measuring the actual letterforms shows that the size is actually 15px. With accessibility standards calling for line-height to be 1.5/150% of the letterform, the adjusted line-height is 22.5px. not 24px. Instead of multiplying at 1.5, the real line-height should be 1.40625rem, which is set as a new css variable.

Adjusting Line Height for Measured Letterform Height

---

tests/test_2fa.py

2fa tests were all using the same test user which seems to occasionally cause issues related to unintended otp rate-limiting. This PR passes a login_data fixture to each test with a pseudo-random username to improve isolation between the tests and avoid accidental rate-limiting.

generate pseudo-random username for each 2fa test

---

.github/workflows/tests.yml

Add the 'pull_request' event trigger in 'tests.yml' for PRs which target 'main' to automatically cause the required basic tests to run.

ci: run basic required tests on 'main' when PRs target it

---

hushline/__init__.py
hushline/templates/base.html

- Update environment variable for IS_PERSONAL_SERVER to be interpreted as a boolean instead of a string. 
- Make Vision a managed service feature only
- Removes third-parties from Personal Server

Vision visibility

---

Makefile
hushline/__init__.py
hushline/admin.py
hushline/make_admin.py
hushline/model.py
hushline/routes.py
hushline/settings.py
hushline/templates/inbox.html
tests/auth_helper.py
tests/test_registration_and_login.py
tests/test_settings.py
tests/test_submit_message.py

The PR refactors the hushline codebase onto sqlalchemy's new session API. This interface ends up looking much more like the sql that it generates and should reduce the "magic" of the query builder. Along with this, I've updated the models to use the new declarative definition, with the main result being improved type-checking.
At the same time, this refactors the deprecated use of `datetime.utcnow()` in favor of `datetime.now(datetime.UTC)`
In the process of refactoring, a few issues were highlighted related to 2fa validation if it doesn't get setup correctly.

Adopt sql alchemy session api

---

hushline/static/css/style.css
hushline/templates/vision.html

- Adds a label for the file input
- Updates CSS to use existing patterns
Before: 
After:

Vision UI Styling

---

.github/workflows/dev_deploy.yml

A dev deploy failed with the error message:
```
Error: expected length of spec.0.name to be in the range (2 - 32), got hushline-dev-proton-key-discovery
```

use shorter DO app names, they are limited to a max of 32 charaters

---

hushline/admin.py
hushline/routes.py
hushline/settings.py
hushline/templates/base.html
hushline/templates/verify_2fa_login.html
hushline/utils.py
tests/test_settings.py

While implementing an unrelated feature I discovered a bunch of problems and inconsistencies with the routes, as they're defined. This PR tries to fix as many of them as possible. It does the following:
Many of the routes included the confusingly-named `@require_2fa` decorator, even routes that were unrelated to 2FA. What this route actually did was ensure that the user was logged in, with extra logic to ensure that 2FA was verified if it's enabled. This was all too complicated.
I deleted the `@require_2fa` decorator and made two new ones, `@authentication_required` and `@admin_authentication_required`. If `user_id` is set in the session and `is_authenticated` in the session is true, then the user is logged in. I moved all of the 2FA logic into the login flow itself.
Before, during login …

More strictly enforce authentication, and clean up routes

---

hushline/static/css/style.css

The banner was on top of the flash message before - this fixes that by changing the z-index to 9 to match the fixed header.

Fix Z-Index on Banner

---

hushline/static/css/style.css
hushline/templates/settings.html

Fixes a messy layout when a PGP key hasn't been uploaded
Before:
After:

Fix Forwarding UI When No PGP Key Present

---

hushline/crypto.py
tests/conftest.py

faster scrypt in testing

---

hushline/model.py
hushline/settings/__init__.py
tests/conftest.py
tests/test_profile.py
tests/test_settings.py

Alias tests

---

.github/workflows/tests.yml
Dockerfile.dev
Makefile
package-lock.json

This change runs prettier via docker container. It also defines the scope of prettier to `.md` files in the repo root, github actions workflows, docs, and the hushline directory.

run prettier via docker container

---

Dockerfile.dev

According to the PySequoia v0.1.24 PyPI page, there are no amd64 wheel builds, so we need to compile from source. This changes the requirements, so we need `cargo` for Rust, a whole bunch of .so and header files, and extra build tools.
fixes #620

update dockerfile so pysequoia installs on linux/amd64

---

hushline/templates/settings/index.html

This small PR moves the Branding tab before the Advanced tab.

Change Branding tab order

---

hushline/static/css/style.css
hushline/templates/settings/alias.html

Before we didn't have a way to link to the tip line for an alias if it wasn't already in the directory. This PR addresses that by adding a link on the `alias.html` page under the page heading.

Add link to alias tip line

---

hushline/static/css/style.css
hushline/templates/base.html

The emoji was causing the Upgrade label to be misaligned. This fix moves the emoji outside of the anchor, and positions it absolutely to force alignment of just the text label.
Before:
After:

Upgrade button tweaks

---

hushline/templates/settings/index.html

- Added a `requires_paying_customer` flag to the buttons list in settings.html.
- Updated the loop condition to render tabs based on the user’s tier.
- Adjusted the inclusion of aliases.html to be conditional on the user’s tier.

Temp Fix - Hide Alias Tab for Free Tier

---

hushline/static/css/style.css
hushline/templates/inbox.html

- Smaller encrypted text
- Fix dark mode destructive colors
**Before:**

Style updates

---

hushline/__init__.py
hushline/db.py
pyproject.toml
tests/conftest.py
tests/helpers.py
tests/migrations/revision_46aedec8fd9b.py
tests/migrations/revision_5410668e15ad.py
tests/migrations/revision_be0744a5679f.py
tests/test_migrations.py

Automatically test all (new) migrations.
This is a WIP for initial review. I'd forgotten what a pain in the ass it is to write these kinds of tests, so I wanted to get a sensibility check before I finished.
fixes #555

Auto testing of migrations

---

docker-compose.staging.yaml
hushline/premium.py
scripts/prod_start.sh

Should help with #657.
I still haven't pinned down exactly why staging releases weren't working (and the latest PR that merged into main did work), but this PR should at least help. I think the issue is in part related to the containers in the staging environment not have any dependencies, so they all start up in a random order.
The worker container was crashing because it was starting before migrations happened, so this waits for migrations to finish before actually starting the worker. I also added a new docker-compose.yaml file which starts the containers in production mode, to more closely resemble what happens on staging and prod, to be able to test locally.

Wait for migrations before starting worker

---

hushline/settings/__init__.py
tests/conftest.py
tests/test_settings.py

Fixes #660 in the simplest way possible without changing the overall logic/structuring of the app.
Follow up ticket: #661

delete auth logs when deleting a user

---

hushline/static/css/style.css

Fix Dark Mode Upgrade Banner

---

Makefile
docker-compose.staging.yaml
docker-compose.stripe.yaml
docker-compose.yaml
docs/config.md
hushline/__init__.py
hushline/routes.py
hushline/static/js/directory.js
hushline/static/js/directory_verified.js
hushline/templates/base.html
hushline/templates/directory.html
hushline/templates/personal_server_info.html
hushline/templates/premium-select-tier.html
hushline/templates/premium.html
hushline/templates/server_info.html
hushline/templates/settings/email.html
tests/conftest.py
tests/test_info.py

fixes #646
fixes #626 
- Removes `IS_PERSONAL_SERVER` flag and `is_personal_server` jinja var
- Removes hardcoded riseup.net text and replaces with `SMTP_FORWARDING_MESSAGE_HTML` env var
- Changes logic for `/directory` route to use `DIRECTORY_VERIFIED_TAB_ENABLED` env var instead of `IS_PERSONAL_SERVER`
- Removes `ProxyFix` that has dubiously correct settings with unused results
- Detects "personal server / Tor" via `request.host`
- renamed JS files (didn't change them, but the diff thinks I did)
- adds docs for all currently supported configs (others exist, but they're purposely undocumented so we don't have to support them)

Replace is_personal_server flag

---

docs/config.md
hushline/config.py
hushline/templates/settings/aliases.html

- makes `ENCRYPTION_KEY` not requires
- updates docs to reflect currently required config values

Config parsing fix & docs updates

---

.github/workflows/build-and-deploy-latest.yml
.github/workflows/build-and-deploy-release.yml

When building a `latest` or `release` docker image, this pushes the image to a private DigitalOcean Container Registry as well as the public GitHub Container Registry.
Note: I haven't tried running this in GitHub Actions, but I have manually authenticated to DOCR using a DO token and pushed images to this container registry using the same commands, so I expect it will work.

Push container images to DigitalOcean Container Registry

---

.github/workflows/build-and-deploy-latest.yml
.github/workflows/build-and-deploy-release.yml

This stops trying to publish to DigitalOcean Container Registry, and instead publishes to Docker Hub here: https://hub.docker.com/r/scidsg/hushline
I tested it out by making build-and-deploy-latest.yml deploy `latest` on the `dockerhub` branch, rather than just the `main` branch, and it works. Here's the job where it pushed to Docker Hub: https://github.com/scidsg/hushline/actions/runs/11467211631/job/31909592576
You can pull the container from Docker Hub with: `docker pull scidsg/hushline:latest`

Publish to Docker Hub

---

hushline/static/css/style.css
hushline/static/js/settings.js
hushline/templates/settings/index.html

When there are 5 or more items in the Settings nav tab set, the tabs display as a column instead of a row, and the settings content to the right rather than underneath.
At 640px, the display changes back to tabs as a row which are horizontally scrollable.

Settings Nav Display Logic

---

hushline/routes.py
tests/test_inbox.py

This PR fixes #747 - a bug in the `delete_message` route where messages could not be deleted due to incorrect conditions in the `where` clause, resulting in “Message not found” errors even for valid requests. The bug fix includes modifying the query to properly associate messages with the authenticated user’s primary `Username`.
1. Bug Fix in `delete_message` Route:
• Adjusted the `where` clause in the `delete_message` function to check for the `correct username_id` associated with the authenticated user’s `User` object.
• Added logging statements to aid in troubleshooting future issues with message deletion, including logging the `message_id` and `user_id`.
2. Unit Test for delete_message Route:
• Created a new unit test (`test_delete_message`) in `tests/test_inbox.py` to validate the …

Fix `delete_message` bug

---

hushline/static/css/style.css
hushline/static/js/global.js
hushline/templates/base.html

- Removed hardcoded values
- Removed JS that was causing the correct color to be overwritten
**Before:**
**After:**

Remove hardcoded theme values

---

hushline/static/js/global.js

The global navigation menu was not functioning on responsive (mobile) sizes. Clicking the “Menu” button had no effect due to missing JavaScript handling for toggling the mobile navigation menu.
- Added setupMobileNav() function:
- Selects the mobile navigation button (`.mobileNav`) and the navigation menu list (`header nav ul`).
- Adds a click event listener to the mobile navigation button.
- Toggles the show class on the navigation `<ul>` to control menu visibility, matching the existing CSS.
- Adjusted `navController()` function:
- Called the new `setupMobileNav()` function to initialize mobile navigation handling.
- The mobile navigation menu now works correctly on responsive sizes.
- Clicking the “Menu” button toggles the visibility of the navigation menu as expected.
- The navigation …

Fix Responsive Global Nav

---

.github/workflows/tests.yml

Closes #623 
This PR limits the runs of the `tests` on `push` events; only pushes to `main` will trigger the workflow (in addition to pull_request events).
In addition, this PR teases out the test-related steps to separate jobs so they can be run in parallel as they are not dependent on each other (afict) with the goal of reducing total runtime of the workflow and creating a quicker feedback loop as we cannot get test results in CI until the linters run on the codebase. If we look at the latest run vs previous in https://github.com/scidsg/hushline/actions/workflows/tests.yml , seems we can reduce by at least a minute.

chore: runs tests on PRs and pushes to main; run tests and linters in parallel

---

docker-compose.staging.yaml
docker-compose.stripe.yaml
docker-compose.yaml
docs/README.md
hushline/__init__.py
hushline/config.py
hushline/secure_session.py
tests/conftest.py
tests/test_secure_session.py

Overrides the default session interface to use on that is encrypted and timed via Fernet. The logic largely copies the internal logic of Flask's default `SecureSessionInterface`, so comparison should be quite easy.
Flask Docs: https://flask.palletsprojects.com/en/3.0.x/api/#flask.sessions.SessionInterface
Fixes #603

fernet encrypted sessions

---

hushline/__init__.py

Fix AttributeError when `SERVER_NAME` is `None` in `add_security_header`.
- Updated `if not app.config.get("SERVER_NAME", "").endswith(".onion")` to safely handle `None` values using or `""`.
- Ensures compatibility when `SERVER_NAME` is not set in app.config.
Changes:
- 1 addition, 1 deletion in hushline/__init__.py.
- Prevents errors caused by calling `.endswith()` on `None`.

Fix AttributeError for SERVER_NAME when unset in add_security_header

---

.github/workflows/tests.yml
Dockerfile.dev

This fixes the github actions workflow fail problems. Something changed with poetry, or with pip, and now running `poetry install` inside the dev container is failing. This fixes it by changing it to `poetry install --no-root`.

Fix github actions workflow fail

---

Makefile
docker-compose.staging.yaml
docker-compose.stripe.yaml
docker-compose.yaml
scripts/dev_data.py

fix makefile migrations

---

README.md
docs/README.md
hushline/config.py
hushline/routes/profile.py
hushline/routes/submit.py
hushline/templates/profile.html
tests/conftest.py
tests/test_profile.py
tests/test_settings.py

Please double check the logic changes in `hushline/templates/profile.html`.

Remove REQUIRE_PGP env var and instead always require PGP

---

hushline/templates/inbox.html

Moves classes to the `<a>` instead of the `<li>`.

Update Tab Class Placement

---

docker-compose.personal-server.yaml
hushline/routes/auth.py
hushline/routes/index.py
hushline/static/css/style.css
hushline/templates/register.html
hushline/templates/settings/profile.html
tests/helpers.py
tests/test_first_user.py
tests/test_registration_and_login.py

Fixes #972 and #975
I've added a new docker compose file, `docker-compose.personal-server.yaml`, to simulate the personal server. Specifically, I needed to be able to test this in dev mode but without dev data. You can test with:
```sh
docker compose -f docker-compose.personal-server.yaml up --build
```
This does a few things:
When loading the index, if there are no users, it redirects to the register page.
If there are no users, the register page shows a special alert to create the first admin user:
For the styles, I decided to make the alert look just like the upgrade buttons in settings. To do this, I renamed the `upgrade` class to `alert` so we can re-use this style in other places.
When creating the first user, it make the user an admin, and it also by default adds the user's primary …

First user automatically becomes an admin

---

docs/README.md
hushline/admin.py
hushline/config.py
hushline/settings/admin.py
hushline/templates/settings/admin.html
tests/conftest.py
tests/test_admin.py

Fixes #980.
This create a new environment variable `MANAGED_SERVICE` which defaults to false. If `MANAGED_SERVICE` is false, it hides the toggle verified button in settings, and it returns 401 if you try accessing the route.
Because this adds a new environment variable, we need to make sure to set it when we deploy the update to the managed service. This doesn't require any changes for updating the personal server because `MANAGED_SERVICE` defaults to false.

Reserve verified users for the managed service

---

.github/workflows/build-latest.yml
.github/workflows/build-release.yml
.github/workflows/bypass-review.yaml
.github/workflows/dev_deploy.yml
.github/workflows/post-to-mastodon.yml
.github/workflows/tests.yml

Add a top-level permissions: block to every workflow to scope GITHUB_TOKEN to only the APIs each job needs. Clears CodeQL “missing-workflow-permissions” alerts and aligns with the principle of least privilege.
• .github/workflows/dev_deploy.yml
• .github/workflows/tests.yml
• .github/workflows/post-to-mastodon.yml
• .github/workflows/build-release.yml
• .github/workflows/build-latest.yml
• .github/workflows/bypass-review.yaml
• contents: read for all workflows using actions/checkout
• pull-requests: write & issues: write where we add/remove labels or post comments
• packages: write for container builds/pushes
• contents: none in Mastodon post (no GitHub API calls)

 Enforce least-privilege `GITHUB_TOKEN` in all workflows

---

hushline/model/authentication_log.py
hushline/model/field_definition.py
hushline/model/field_value.py
hushline/model/invite_code.py
hushline/model/message.py
hushline/model/message_status_text.py
hushline/model/stripe_event.py
hushline/model/stripe_invoice.py
hushline/model/tier.py
hushline/model/user.py
hushline/model/username.py

Fixes #870 
Now when you create an autogenerated alembic migration, it doesn't create a migration at all.
It still has a few warnings though which I'm not sure how to get rid of, but I think we can safely ignore:
```
INFO  [alembic.ddl.postgresql] Detected sequence named 'message_id_seq' as owned by integer column 'messages(id)', assuming SERIAL and omitting
INFO  [alembic.ddl.postgresql] Detected sequence named 'invite_code_id_seq' as owned by integer column 'invite_codes(id)', assuming SERIAL and omitting
INFO  [alembic.ddl.postgresql] Detected sequence named 'authentication_logs_id_seq' as owned by integer column 'authentication_logs(id)', assuming SERIAL and omitting
INFO  [alembic.ddl.postgresql] Detected sequence named 'field_definitions_id_seq' as owned by integer column …
```

Update models to match the current state of the db

---

assets/js/global.js
assets/js/service-worker.js

This PR introduces minimal PWA functionality to improve mobile and desktop installability:
• Added `assets/js/service-worker.js` with basic caching (homepage, CSS, favicon) for faster load and offline support.
• Registered service worker in `global.js` for automatic activation on supported browsers.
• Ensured service worker registration does not interfere with other scripts and runs only when supported.
This completes the initial PWA setup:
• Installable on Android, desktop Chrome, Edge.
• Fullscreen standalone display.
• Slight offline capability (static assets cached).
Future improvements (not in this PR):
• Add offline fallback page.

Enable basic PWA support
